Isometriks\Bundle\SymEditBundle\Entity\Chunk:
    type: entity
    table: chunk
    fields:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
        name:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        options:
            type: json_array
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        strategyName:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
            column: strategy_name
    manyToOne:
        page:
            targetEntity: Isometriks\Bundle\SymEditBundle\Entity\Page
            cascade: {  }
            mappedBy: null
            inversedBy: chunks
            joinColumns:
                page_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
