Isometriks\Bundle\SymEditBundle\Entity\Post:
    type: entity
    table: post
    repositoryClass: Isometriks\Bundle\SymEditBundle\Repository\PostRepository
    fields:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
        title:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        slug:
            type: string
            scale: 0
            length: 255
            unique: true
            nullable: false
            precision: 0
        content:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        summary:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        createdAt:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        updatedAt:
            type: datetime
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        status:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        seo:
            type: json_array
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
    manyToOne:
        image:
            targetEntity: Isometriks\Bundle\SymEditBundle\Entity\Image
            cascade:
                - persist
            mappedBy: null
            inversedBy: null
            joinColumns:
                image_id:
                    referencedColumnName: id
            orphanRemoval: false
        author:
            targetEntity: Isometriks\Bundle\SymEditBundle\Model\UserInterface
            cascade: {  }
            mappedBy: null
            inversedBy: posts
            joinColumns:
                author_id:
                    referencedColumnName: id
            orphanRemoval: false
    manyToMany:
        categories:
            targetEntity: Isometriks\Bundle\SymEditBundle\Entity\Category
            cascade: {  }
            mappedBy: null
            inversedBy: posts
            joinTable:
                name: post_category
                joinColumns:
                    -
                        name: post_id
                        referencedColumnName: id
                        onDelete: CASCADE
                inverseJoinColumns:
                    -
                        name: category_id
                        referencedColumnName: id
                        onDelete: CASCADE
            orderBy: null
    lifecycleCallbacks: {  }
