Isometriks\Bundle\UserBundle\Entity\Profile:
    type: entity
    inheritanceType: JOINED
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    discriminatorColumn:
        name: discr
        type: string
        length: 20
    discriminatorMap:
        admin: AdminProfile
    fields:
        firstName:
            type: string
        lastName:
            type: string
            nullable: true
    oneToOne:
        user:
            targetEntity: Isometriks\Bundle\SymEditBundle\Model\UserInterface
            mappedBy: profile