Isometriks\Bundle\SymEditBundle\Entity\User:
    type: entity
    table: users
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    oneToOne:
        profile:
            targetEntity: Isometriks\Bundle\SymEditBundle\Model\ProfileInterface
            inversedBy: user
            cascade: [persist, remove]
