Isometriks\Bundle\UserBundle\Entity\User:
    type: entity
    table: users
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    oneToOne:
        profile:
            targetEntity: Isometriks\Bundle\SymEditBundle\Model\ProfileInterface
            inversedBy: user
            cascade: [persist, remove]
    oneToMany:
        posts:
            targetEntity: Isometriks\Bundle\SymEditBundle\Entity\Post
            cascade: [persist, remove]
            mappedBy: author
            orphanRemoval: false
            orderBy:
                createdAt: DESC
