Isometriks\Bundle\SymEditBundle\Entity\Widget:
    type: entity
    table: widget
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: IDENTITY
        name:
            type: string
            length: 255
            unique: true
            nullable: false
        title:
            type: string
            length: 255
            nullable: true
        options:
            type: json_array
        visibility:
            type: integer
            nullable: false
            default: 0
        assoc:
            type: json_array
        strategyName:
            type: string
            length: 255
            nullable: false
            column: strategy_name
    manyToOne:
        area:
            targetEntity: Isometriks\Bundle\SymEditBundle\Entity\WidgetArea
            inversedBy: widgets
