fos_user:
    db_driver: orm 
    firewall_name: main
    user_class: Isometriks\Bundle\SymEditBundle\Entity\User
    registration:
        form:
            type: isometriks_symedit_user_registration
    profile:
        form:
            type: isometriks_symedit_user_profile
    
mopa_bootstrap:
    form:
        show_legend: false 
        render_required_asterisk: true
        render_optional_text: false

jms_security_extra:
    secure_all_services: false
    expressions: true
    
isometriks_settings:
    twig:
        global: true
        global_variable: Settings
        
twig:
    form:
        resources: 
            - 'IsometriksSymEditBundle:Form:fields.html.twig'
        
doctrine:
    orm:
        resolve_target_entities:
            Isometriks\Bundle\SymEditBundle\Model\UserInterface: Isometriks\Bundle\SymEditBundle\Entity\User
        entity_managers:
            default:
                filters:
                    post_published:
                        class: Isometriks\Bundle\SymEditBundle\Filter\PostPublishedFilter
                        enabled: true