Isometriks\Bundle\SymEditBundle\Model\Page:
    type: entity
    table: pages
    gedmo:
        tree:
          type: materializedPath
    repositoryClass: Isometriks\Bundle\SymEditBundle\Doctrine\Orm\Repository\PageRepository
    fields:
        id:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
            id: true
            generator:
                strategy: IDENTITY
        homepage:
            type: boolean
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        root:
            type: boolean
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        name:
            type: string
            nullable: true
            gedmo:
                - treePathSource
        tagline:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
        summary:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        path:
            type: string
            unique: true
            nullable: true
            gedmo:
                treePath:
                    appendId: false
                    separator: "/"
                    endsWithSeparator: false
        title:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: false
            precision: 0
        content:
            type: text
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        seo:
            type: json_array
            scale: 0
            length: null
            unique: false
            nullable: true
            precision: 0
        pageOrder:
            type: integer
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        display:
            type: boolean
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        crawl:
            type: boolean
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        pageController:
            type: boolean
            scale: 0
            length: null
            unique: false
            nullable: false
            precision: 0
        pageControllerPath:
            type: string
            scale: 0
            length: 255
            unique: false
            nullable: true
            precision: 0
        createdAt:
            type: datetime
            nullable: false
            gedmo:
                timestampable:
                    on: create
        updatedAt:
            type: datetime
            nullable: false
            gedmo:
                timestampable:
                    on: update
        level:
            type: integer
            nullable: true
            gedmo:
                - treeLevel
        lft:
            type: integer
            nullable: true
            gedmo:
                - treeLeft
        rgt:
            type: integer
            nullable: true
            gedmo:
                - treeRight
        template:
            type: string
            nullable: true
    indexes:
        path_index:
            columns: [path]
    manyToOne:
        parent:
            targetEntity: Isometriks\Bundle\SymEditBundle\Model\Page
            cascade: {  }
            mappedBy: null
            inversedBy: children
            joinColumns:
                parent:
                    referencedColumnName: id
                    onDelete: 'SET NULL'
            orphanRemoval: false
            gedmo:
                - treeParent
    oneToMany:
        children:
            targetEntity: Isometriks\Bundle\SymEditBundle\Model\Page
            cascade:
                - remove
                - persist
            mappedBy: parent
            inversedBy: null
            orphanRemoval: false
            orderBy:
                pageOrder: ASC
#    lifecycleCallbacks:
#        prePersist:
#            - fixPath
