fos_user:
    db_driver: orm
    firewall_name: main
    user_class: SymEdit\Bundle\CoreBundle\Model\User
    service:
        mailer: isometriks_symedit.mailer
        user_manager: isometriks_symedit.manager.user
    registration:
        confirmation:
            enabled: true
            template: "@SymEdit/Email/confirm.html.twig"
        form:
            type: symedit_user_registration
    resetting:
        email:
            template: "@SymEdit/Email/resetting.html.twig"