imports:
    - { resource: config.yml }

framework:
    test: ~
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }
    session:
            storage_id: session.storage.mock_file

assetic:
    use_controller: true

web_profiler:
    toolbar: false

swiftmailer:
    disable_delivery: true

security:
    firewalls:
        main:
            http_basic: ~
            anonymous: true

    access_control:
        - { path: ^/sym-admin, role: ROLE_ADMIN }

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - ROLE_SUPER_EXTEND
            - ROLE_ADMIN_BLOG
            - ROLE_ADMIN_WIDGET
            - ROLE_ADMIN_IMAGE
            - ROLE_ADMIN_SETTING
            - ROLE_ADMIN_PAGE
            - ROLE_ADMIN_USER
            - ROLE_ADMIN_WEBMASTER
            - ROLE_ADMIN_EDITABLE
            - ROLE_ADMIN_STYLIZER
