imports:
    - { resource: config.yml }
    - { resource: security.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

assetic:
    use_controller: true

web_profiler:
    toolbar: true
