imports:
    - { resource: config.yml }

parameters:
    security.user.provider.in_memory.class: SymEdit\Bundle\CoreBundle\Tests\Security\InMemoryUserProvider

framework:
    test: ~
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

assetic:
    use_controller: true

web_profiler:
    toolbar: false

swiftmailer:
    disable_delivery: true

security:
    firewalls:
        main:
            pattern: ^/
            http_basic: ~

    providers:
        in_memory:
            memory:
                users:
                    admin: { password: foo, roles: 'ROLE_SUPER_ADMIN' }

    encoders:
        FOS\UserBundle\Model\UserInterface: plaintext
