doctrine:
    orm:
        resolve_target_entities:
            Isometriks\Bundle\SymEditBundle\Model\UserInterface: %isometriks_sym_edit.entity.user_class%
        entity_managers:
            default:                    
                filters:
                    post_published:
                        class: Isometriks\Bundle\SymEditBundle\Filter\PostPublishedFilter
                        enabled: true
                        
stof_doctrine_extensions:
    orm:
        default:
            timestampable: true
            sluggable: true
            blameable: true
            tree: true