fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Isometriks\Bundle\SymEditBundle\Model\User
    service:
        mailer: isometriks_symedit.mailer
        user_manager: isometriks_symedit.user_manager
    registration:
        confirmation:
            enabled: true
            template: "@SymEdit/Email/confirm.html.twig"
        form:
            type: %isometriks_symedit.fos_user.form.registration%
    resetting:
        email:
            template: "@SymEdit/Email/resetting.html.twig"