parameters:
    
    # Profile Entity Class
    isometriks_symedit.entity.profile_class:       Isometriks\Bundle\UserBundle\Model\Profile
    isometriks_symedit.entity.admin_profile_class: Isometriks\Bundle\UserBundle\Model\AdminProfile
    
    # FOS Parameters
    isometriks_symedit.fos_user.form.registration: symedit_user_registration
    isometriks_symedit.fos_user.form.profile:      symedit_user_profile
            
    # Admin Dir 
    isometriks_symedit.admin_dir:                  /sym-admin