parameters:
    # User Entity Class
    isometriks_symedit.entity.user_class:          Isometriks\Bundle\SymEditBundle\Model\User
    
    # Profile Entity Class
    isometriks_symedit.entity.profile_class:       Isometriks\Bundle\UserBundle\Entity\Profile
    isometriks_symedit.entity.admin_profile_class: Isometriks\Bundle\UserBundle\Entity\AdminProfile
    
    # FOS Parameters
    isometriks_symedit.fos_user.form.registration: symedit_user_registration
    isometriks_symedit.fos_user.form.profile:      symedit_user_profile
            
    # Admin Dir 
    isometriks_symedit.admin_dir:                  /sym-admin