sylius_resource:
    resources:
        # Pages
        isometriks_symedit.page:
            driver: doctrine/orm
            classes:
                model: Isometriks\Bundle\SymEditBundle\Model\Page
                controller: Isometriks\Bundle\SymEditBundle\Controller\Admin\PageController

        # Posts
        isometriks_symedit.post:
            driver: doctrine/orm
            classes:
                model: Isometriks\Bundle\SymEditBundle\Model\Post