seo:
    label: SEO
    settings:
        head_extra:
            type: textarea
            options:
                label: Extra <head> tag contents
                required: false
                attr:
                    rows: 5
        business_type:
            type: choice
            default: LocalBusiness
            options:
                label: Business Type
                choices:
                    LocalBusiness:                  Local Business (Default)
                    AnimalShelter:                  Animal Shelter
                    AutomotiveBusiness:             Automotive Business
                    ChildCare:                      Child Care
                    DryCleaningOrLaundry:           Dry Cleaning / Laundry
                    EmergencyService:               Emergency Service
                    EmploymentAgency:               Employment Agency
                    EntertainmentBusiness:          Entertainment
                    FinancialService:               Financial Service
                    FoodEstablishment:              Food Establishment
                    Bakery:                         -- Bakery
                    BarOrPub:                       -- Bar / Pub
                    Brewery:                        -- Brewery
                    CafeOrCoffeeShop:               -- Cafe / Coffee Shop
                    FastFoodRestaurant:             -- Fast Food Restaurant
                    IceCreamShop:                   -- Ice Cream Shop
                    Restaurant:                     -- Restaurant
                    Winery:                         -- Winery
                    GovernmentOffice:               Government Office
                    HealthAndBeautyBusiness:        Health and Beauty
                    HomeAndConstructionBusiness:    Home and Construction
                    InternetCafe:                   Internet Cafe
                    Library:                        Library
                    LodgingBusiness:                Lodging Business
                    MedicalOrganization:            Medical Organization
                    ProfessionalService:            Professional Service
                    RadioStation:                   Radio Station
                    RealEstateAgent:                RealEstateAgent
                    RecyclingCenter:                Recycling Center
                    SelfStorage:                    Self Storage
                    ShoppingCenter:                 Shopping Center
                    SportsActivityLocation:         Sports Activity Location
                    Store:                          Store
                    AutoPartsStore:                 -- Auto Parts
                    BikeStore:                      -- Bike Store
                    BookStore:                      -- Book Store
                    ClothingStore:                  -- Clothing Store
                    ComputerStore:                  -- Computer Store
                    ConvenienceStore:               -- Convenience Store
                    DepartmentStore:                -- Department Store
                    ElectronicsStore:               -- Electronics
                    Florist:                        -- Florist
                    FurnitureStore:                 -- Furniture Store
                    GardenStore:                    -- Garden Store
                    GroceryStore:                   -- Grocery Store
                    HardwareStore:                  -- Hardware Store
                    HobbyShop:                      -- Hobby Shop
                    HomeGoodsStore:                 -- Home Goods
                    JewelryStore:                   -- Jewelry Store
                    LiquorStore:                    -- Liquor Store
                    MensClothingStore:              -- Mens Clothing
                    MobilePhoneStore:               -- Mobile Phone Store
                    MovieRentalStore:               -- Movie Rental
                    MusicStore:                     -- Music Store
                    OfficeEquipmentStore:           -- Office Equipment
                    OutletStore:                    -- Outlet Store
                    PawnShop:                       -- Pawn Shop
                    PetStore:                       -- Pet Store
                    ShoeStore:                      -- Shoe Store
                    SportingGoodsStore:             -- Sporting Goods
                    TireShop:                       -- Tire Shop
                    ToyStore:                       -- Toy Store
                    WholesaleStore:                 -- Wholesale Store
                    TelevisionStation:              Television Station
                    TouristInformationCenter:       Tourist Information Center
                    TravelAgency:                   Travel Agency
