company:
    label: Company
    settings:
        name:
            options:
                label: Company Name
            default: SymEdit Site
        address:
            default: 5 SymEdit Way
            type: textarea
            options:
                required: false
                attr:
                    rows: 3
        email:
            default: contact@mysite.com
            options:
                label: Contact Email
        phone:
            default: (123)-123-1234
            options:
                required: false
        fax:
            options:
                required: false

social:
    label: Social Media
    default_options:
        required: false
    settings:
        facebook:
            type: url
            options:
                attr:
                    placeholder: "http://facebook.com"

        twitter:
            type: url
            options:
                attr:
                    placeholder: "http://twitter.com"

        youtube:
            type: url
            options:
                label: 'YouTube'
                attr:
                    placeholder: "http://youtube.com"

        google_plus:
            type: url
            options:
                label: 'Google+'
                attr:
                    placeholder: "http://plus.google.com"

        linkedin:
            type: url
            options:
                label: LinkedIn
                attr:
                    placeholder: "http://linkedin.com"
        pinterest:
            type: url
            options:
                label: Pinterest
                attr:
                    placeholder: "http://pinterest.com"
        instagram:
            type: url
            options:
                label: Instagram
                attr:
                    placeholder: "http://instagram.com"

webmaster:
    label: Webmaster
    role: ROLE_ADMIN_WEBMASTER
    default_options:
        required: false
    settings:
        google_analytics_enabled:
            type: choice
            default: true
            options:
                required: true
                choices:
                    true: Enabled
                    false: Disabled
                label: Enable Google Analytics
                attr:
                    class: ~
        google_analytics:
            options:
                label: Google Analytics Code
                attr:
                    placeholder: UA-12345678
        google_verify:
            options:
                label: Google Verification
                attr:
                    placeholder: google123456789012
        bing_verify:
            options:
                label: Bing Verification
        robots:
            type: choice
            default: deny
            options:
                required: true
                choices:
                    deny: Deny All
                    allow: Allow All

advanced:
    label: Advanced
    role: ROLE_SUPER_ADMIN
    settings:
        caching:
            type: choice
            options:
                choices:
                    none: No Cache
                    cache: Cache
        ttl:
            type: integer
            default: 120
            options:
                label: Maximum Cache Time
