SymEdit\Bundle\CoreBundle\Model\User:
    properties:
        profile:
            - Valid: ~
    constraints:
          - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email

SymEdit\Bundle\CoreBundle\Model\Page:
    constraints:
        - Callback:
            methods: [isNameValid, isParentValid]
    properties:
        title:
            - NotBlank:
                message: "You must provide a Title for this Page"
        name:
            - Regex:
                pattern: "/^[a-z0-9_-]+$/"
                message: "You may only use lowercase letters, numbers, underscores or hyphens"

SymEdit\Bundle\CoreBundle\Model\Slider:
    properties:
        name:
            - Regex:
                pattern: "/^[a-z0-9_-]+$/"
                message: "You may only use lowercase letters, numbers, underscores or hyphens"
        description:
            - NotBlank: ~