admin_image_gallery:
    pattern: /
    methods: [GET]
    defaults:
        _controller: symedit.controller.image_gallery:indexAction
        _sylius:
            template: @SymEdit/Admin/ImageGallery/index.html.twig
            paginate: false
            limit: false

admin_image_gallery_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: symedit.controller.image_gallery:createAction
        _sylius:
            template: @SymEdit/Admin/ImageGallery/new.html.twig
            redirect:
                route: admin_image_gallery_update
                parameters: { id: $id }

admin_image_gallery_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: symedit.controller.image_gallery:updateAction
        _sylius:
            template: @SymEdit/Admin/ImageGallery/edit.html.twig
            redirect:
                route: admin_image_gallery_update
                parameters: { id: $id }

# Gallery Item Routes
admin_gallery_item_create:
    pattern: /{gallery_id}/item/new
    methods: [GET, POST]
    defaults:
        _controller: symedit.controller.gallery_item:createAction
        _sylius:
            template: @SymEdit/Admin/ImageGallery/Item/new.html.twig
            redirect:
                route: admin_image_gallery_update
                parameters: { id: $gallery_id }

admin_gallery_item_update:
    pattern: /item/{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: symedit.controller.gallery_item:updateAction
        _sylius:
            template: @SymEdit/Admin/ImageGallery/Item/edit.html.twig
            redirect:
                route: admin_gallery_item_update
                parameters: { id: $id }

admin_gallery_item_delete:
    pattern: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: symedit.controller.gallery_item:deleteAction
        _sylius:
            redirect: admin_image_gallery