admin_image:
    pattern: /
    methods: [GET]
    defaults:
        _controller: symedit.controller.media:indexAction
        _sylius:
            template: @SymEdit/Admin/Image/index.html.twig
            paginate: false
            limit: false

admin_image_json:
    pattern: /list.{_format}
    requirements:
        _format: json
    defaults:
        _format: json
        _controller: symedit.controller.media:indexAction
        _sylius:
            paginate: false

admin_image_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: symedit.controller.media:createAction
        _sylius:
            template: @SymEdit/Admin/Image/new.html.twig
            redirect: admin_image

admin_image_quick_upload:
    pattern: /quick-upload
    methods: [POST]
    defaults:
        _controller: symedit.controller.media:quickUploadAction

admin_image_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: symedit.controller.media:updateAction
        _sylius:
            template: @SymEdit/Admin/Image/edit.html.twig
            redirect:
                route: admin_image_update
                parameters: { id: $id }