admin_page:
    pattern: /
    methods: [GET]
    defaults:
        _controller: symedit.controller.page:indexAction
        _sylius:
            paginate: false
            repository:
                method: findRoot
            template: @SymEdit/Admin/Page/index.html.twig

admin_page_json:
    pattern: /list.{_format}
    requirements:
        _format: json
    defaults:
        _format: json
        _controller: symedit.controller.page:jsonAction
        _sylius:
            paginate: false

admin_page_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: symedit.controller.page:createAction
        _sylius:
            template: @SymEdit/Admin/Page/new.html.twig
            redirect:
                route: admin_page_update
                parameters: { id: resource.id }

admin_page_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: symedit.controller.page:updateAction
        _sylius:
            template: @SymEdit/Admin/Page/edit.html.twig
            redirect:
                route: admin_page_update
                parameters: { id: $id }

admin_page_delete:
    pattern: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: symedit.controller.page:deleteAction
        _sylius:
            redirect: admin_page

admin_page_reorder:
    pattern: /reorder
    methods: [POST]
    defaults:
        _controller: symedit.controller.page:reorderAction
        _sylius:
            sortable_position: pageOrder
