admin_post:
    pattern: /
    methods: [GET]
    defaults:
        _controller: symedit.controller.post:indexAction
        _sylius:
            template: @SymEdit/Admin/Post/index.html.twig
            paginate: 10
            sorting:
                createdAt: desc

admin_post_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: symedit.controller.post:createAction
        _sylius:
            template: @SymEdit/Admin/Post/new.html.twig
            redirect:
                route: admin_post_update
                parameters: { id: resource.id }

admin_post_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: symedit.controller.post:updateAction
        _sylius:
            template: @SymEdit/Admin/Post/edit.html.twig
            redirect:
                route: admin_post_update
                parameters: { id: $id }

admin_post_delete:
    pattern: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: symedit.controller.post:deleteAction
        _sylius:
            redirect: admin_post