admin_settings:
    pattern: /
    methods: [GET]
    defaults:
        _controller: symedit.controller.settings:indexAction

admin_settings_update:
    pattern: /
    methods: [PUT, POST]
    defaults:
        _controller: symedit.controller.settings:updateAction
