admin_image_slider:
    pattern: /
    methods: [GET]
    defaults:
        _controller: isometriks_symedit.controller.slider:indexAction
        _sylius:
            template: @SymEdit/Admin/Slider/index.html.twig
            paginate: 10

admin_image_slider_create:
    pattern: /new
    methods: [GET, POST]
    defaults:
        _controller: isometriks_symedit.controller.slider:createAction
        _sylius:
            template: @SymEdit/Admin/Slider/new.html.twig
            redirect:
                route: admin_image_slider_update
                parameters: ~

admin_image_slider_update:
    pattern: /{id}/edit
    methods: [GET, PUT, POST]
    defaults:
        _controller: isometriks_symedit.controller.slider:updateAction
        _sylius:
            template: @SymEdit/Admin/Slider/edit.html.twig
            redirect:
                route: admin_image_slider_update
                parameters: { id: $id }

admin_image_slider_delete:
    pattern: /{id}/delete
    methods: [DELETE]
    defaults:
        _controller: isometriks_symedit.controller.slider:deleteAction
        _sylius:
            redirect: admin_image_slider