SymEdit\Bundle\CoreBundle\Model\User:
    type: entity
    table: users
    id:
        id:
            type: integer
            generator:
                strategy: IDENTITY
    fields:
        admin:
            type: boolean
    oneToOne:
        profile:
            targetEntity: SymEdit\Bundle\CoreBundle\Model\ProfileInterface
            inversedBy: user
            cascade: [persist, remove]
