# We need to explicitly define the SymEdit routes,
# When you extend the bundle and have your own "Admin" directory
# it will just use only those controllers. If any of these are replaced it
# will override correctly.

symedit_admin_page_controller:
    resource: "@IsometriksSymEditBundle/Resources/config/routing/admin/page.yml"

symedit_admin_post_controller:
    resource: "@IsometriksSymEditBundle/Resources/config/routing/admin/post.yml"

symedit_admin_image_controller:
    resource: "@IsometriksSymEditBundle/Resources/config/routing/admin/image.yml"

symedit_admin_category_controller:
    resource: "@IsometriksSymEditBundle/Resources/config/routing/admin/category.yml"

symedit_admin_settings_controller:
    resource: "@IsometriksSymEditBundle/Resources/config/routing/admin/settings.yml"

symedit_admin_user_controller:
    resource: "@IsometriksSymEditBundle/Resources/config/routing/admin/user.yml"

symedit_admin_widget_controller:
    resource: "@IsometriksSymEditBundle/Resources/config/routing/admin/widget.yml"

# Below not converted

symedit_admin_dashboard_controller:
    resource: "@IsometriksSymEditBundle/Controller/Admin/DashboardController.php"
    type: annotation

symedit_admin_slide_controller:
    resource: "@IsometriksSymEditBundle/Controller/Admin/SlideController.php"
    type: annotation

symedit_admin_slider_controller:
    resource: "@IsometriksSymEditBundle/Controller/Admin/SliderController.php"
    type: annotation

symedit_admin_stylizer_controller:
    resource: "@IsometriksSymEditBundle/Controller/Admin/StylizerController.php"
    type: annotation