blog:
    pattern: /
    defaults:
        _controller: symedit.controller.post:indexAction
        _format: html
        _sylius:
            paginate: "#blog.max_posts#"
            template: @SymEdit/Blog/index.html.twig
            criteria:
                status: 1

blog_rss:
    pattern: /feed.xml
    defaults:
        _format: rss
        _controller: symedit.controller.post:indexAction
        _sylius:
            template: @SymEdit/Blog/feed.xml.twig
            paginate: false

blog_archive:
    pattern: /archive/{page}
    defaults:
        _sylius:
            paginate: "#blog.max_posts#"
            template: @SymEdit/Blog/index.html.twig
            criteria:
                status: 1
        _controller: symedit.controller.post:indexAction
        _format: html
        _seo:
            index: false
        page: 1

blog_preview:
    pattern: /preview/{slug}
    defaults:
        _sylius:
            template: @SymEdit/Blog/single.html.twig
            criteria:
                slug: $slug
        _controller: symedit.controller.post:previewAction

blog_slug_view:
    pattern: /{slug}
    requirements:
        slug: "[a-z0-9_-]+"
    defaults:
        _controller: symedit.controller.post:showAction
        _sylius:
            template: @SymEdit/Blog/single.html.twig
            criteria:
                slug: $slug
                status: 1

blog_category_view:
    pattern: /category/{slug}/{page}
    requirements:
        page: \d+
        slug: "[a-z0-9_-]+?"
    defaults:
        _controller: symedit.controller.post:showCategoryAction
        _format: html
        _sylius:
            paginate: "#blog.max_posts#"
            template: @SymEdit/Blog/category.html.twig
        page: 1

blog_category_rss:
    pattern: /category/{slug}/feed.xml
    defaults:
        _controller: symedit.controller.post:showCategoryAction
        _format: rss
        _sylius:
            template: @SymEdit/Blog/feed.xml.twig
        page: 1