contact:
    pattern: /
    defaults:
        _controller: symedit.controller.contact:indexAction

contact_success:
    pattern: /success
    defaults:
        _controller: symedit.controller.contact:successAction
