robots:
    path: /robots.{_format}
    requirements:
        _format: txt
    defaults:
        _controller: SymEditBundle:Crawler:robots
        _format: txt

sitemap:
    path: /sitemap.{_format}
    requirements:
        _format: xml
    defaults:
        _controller: SymEditSitemapBundle:Sitemap:index
        _format: xml
