symedit_blog_controller:
    resource: "@SymEditBundle/Resources/config/routing/frontend/blog.yml"

symedit_contact_controller:
    resource: "@SymEditBundle/Resources/config/routing/frontend/contact.yml"

symedit_team_controller:
    resource: "@SymEditBundle/Resources/config/routing/frontend/team.yml"

symedit_crawler_controller:
    resource: "@SymEditBundle/Resources/config/routing/frontend/crawler.yml"

symedit_webmaster_controller:
    resource: "@SymEditBundle/Resources/config/routing/frontend/webmaster.yml"
