
# These are here instead so you can override the default routing.yml in your
# child bundles and just include this from there.

symedit_fos:
    resource: "@SymEditBundle/Resources/config/routing/fos.yml"

symedit_admin:
    resource: "@SymEditBundle/Resources/config/routing/admin.yml"
    prefix: %symedit.admin_dir%

symedit_pages:
    resource: SymEditBundle:Page
    type: symedit_pages

symedit_controllers:
    resource: "@SymEditBundle/Resources/config/routing/frontend.yml"